---
title: "k-means"
author: "Timothy P Morris"
date: "10/21/2021"
output: html_document
description: -means clustering of NIH toolbox motor measures as a 'phenogrouping' exercise to ask whether a specific profile of motor abitlies is predictive of cogntive and brain health in children. 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#load libraries
```{r}
library(tidyverse)
library(tidymodels)
library(psych)
library(corrr)
library(nlme)
library(ggstatsplot)
library(caret)
```
#load datasets (see each chunk for creation of each)
```{r}
# setwd("/work/cbhlab/Tim/hcp-d") 
load(file = "hcpd.Rdata") # all hcpd data from EDA.rmd
hd8 <- hcpd %>% dplyr::filter(hcpd$age < 8)
load(file = "hd8.Rdata") # hcpd minus those under age 8 and three outliers of grip 
```
# 
```{r}
# for variable creation info and how cat vars ect were coded see EDA.rmd code
hd <- hcpd %>% select(subject_id, site.x, gender.x, age.x, agecat1, PA_cat12, bmi, educ, SES, pds_sub_cat, `Cognition Total Composite Score v1.1.Age-Corrected Standard Score`, `Cognition Crystallized Composite v1.1.Age-Corrected Standard Score`, `Cognition Fluid Composite v1.1.Age-Corrected Standard Score`, `NIH Toolbox 2-Minute Walk Endurance Test Age 3+ v2.0.Age-Corrected Standard Score`, `NIH Toolbox 4-Meter Walk Gait Speed Test Age 7+ v2.0.RawScore`, `NIH Toolbox 9-Hole Pegboard Dexterity Test Age 3+ v2.0.Age-Corrected Standard Scores Dominant`, `NIH Toolbox Grip Strength Test Age 3+ v2.0.Age-Corrected Standard Scores Dominant`)

hd <- hd %>%
  rename(site = site.x,
         sex = gender.x,
         age = age.x,
         cog_total = `Cognition Total Composite Score v1.1.Age-Corrected Standard Score`,
         cog_crystal = `Cognition Crystallized Composite v1.1.Age-Corrected Standard Score`,
         cog_fluid = `Cognition Fluid Composite v1.1.Age-Corrected Standard Score`,
         walk_enduro = `NIH Toolbox 2-Minute Walk Endurance Test Age 3+ v2.0.Age-Corrected Standard Score`,
         gait_speed = `NIH Toolbox 4-Meter Walk Gait Speed Test Age 7+ v2.0.RawScore`, 
         dexterity = `NIH Toolbox 9-Hole Pegboard Dexterity Test Age 3+ v2.0.Age-Corrected Standard Scores Dominant`,
         grip_strength = `NIH Toolbox Grip Strength Test Age 3+ v2.0.Age-Corrected Standard Scores Dominant`,
         pds = pds_sub_cat)

hd$pa <- hd$PA_cat12
hd$pa <- as.numeric(hd$pa)
hd$pa[hd$pa == "1"] <- 0
hd$pa[hd$pa >= "2"] <- 1
# remove creative cat
#remove those under age 8
hd8 <- dplyr::filter(hd, age > 7.999)

hd8 <- na.omit(hd8) # hcpd8 is behav ids (n=933),  minus those under age 8 (N=837) with comeplte data (N=596- final)

hd8$agecat <- cut(hd8$age, 
                  breaks=c(-Inf, 11.99, 14.99, Inf), 
                  labels=c("elementary","middle","high"))
```
# EDA of hd8
```{r}
#library(psych)
describe(hd8)

demos <- hd %>%
  select(bmi,
         sex,
         educ,
         age,
         SES,
         pds)
print(kable(hdniih))
pairs.panels(demos)

nih <- hd %>%
  select(walk_enduro, 
         gait_speed,
         dexterity,
         grip_strength)
pairs.panels(toolbox)

# outliers appear in grip_strength var so removed them
hist(hd8$gait_speed)
boxplot(hd8$gait_speed)
# by percentiles
lower_bound <- quantile(hd8$gait_speed, 0, na.rm = TRUE)
lower_bound
upper_bound <- quantile(hd8$gait_speed, 0.995, na.rm = TRUE)
upper_bound
outlier_ind <- which(hd8$gait_speed < lower_bound | hd8$gait_speed > upper_bound)
outlier_ind
hd8[outlier_ind, ]
# by IQR 
#hist(hd8$gait_speed) #histogram of data distribution
#outliers <- boxplot(hd8$gait_speed)$out #box plot showing outliers
#print(outliers)

hd8 <- hd8[ !(hd8$subject_id %in% c("HCD0122317","HCD2344244","HCD2562658")), ]
boxplot(hd8$gait_speed)

#library(corrr)
#library(dplyr)
hd8 %>%
  select(age,bmi:grip_strength) %>%
  na.omit() %>%
  correlate() %>%
  rearrange() %>%
  network_plot(colours = c("orange", "white", "midnightblue"))

save(hd8, file = "hd8.Rdata") # same as above minus three outliers in gait_speed
#load(file = "hd8.Rdata")
```
# k-means clustering of 4 NIH toolbox measures 
```{r}
#unsclaed all vars
toolbox <- hd8 %>%
  select(walk_enduro,
         gait_speed,
         grip_strength,
         dexterity)
#scaled all vars
toolbox <- as_tibble(scale(toolbox))
#unscaled only those vars with T-score

kclust <- kmeans(toolbox, k = 3, )

# run across multiple sizes of k
kclusts <- 
  tibble(k = 1:9) %>%
  mutate(
    kclust = map(k, ~kmeans(toolbox, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, toolbox)
  )

kclusts

# tidy output across k sizes
clusters <- 
  kclusts %>%
  unnest(cols = c(tidied))

assignments <- 
  kclusts %>% 
  unnest(cols = c(augmented))

clusterings <- 
  kclusts %>%
  unnest(cols = c(glanced))

#plot with two vars each time
p1 <- 
  ggplot(assignments, aes(x = dexterity, y = walk_enduro)) +
  geom_point(aes(color = .cluster), alpha = 0.8) + 
  geom_point(data = clusters, size = 10, shape = "x") +
  facet_wrap(~ k)
p1

#scree plot
ggplot(clusterings, aes(k, tot.withinss)) +
  geom_line() +
  geom_point()

# choose final k based on plots and scree plot FOR @ 
set.seed(758)
final_clust <- kmeans(toolbox, centers = 2)
final_clust
hd8$cluster <- final_clust$cluster

#create df of center of clusters values
centers <- as_tibble(final_clust[["centers"]])
centers$cluster = c(1,2)

#2 clusters
centers_long <- centers %>%
  pivot_longer(!cluster, names_to = "scale", values_to = "score")

centers_long$cluster <- as.factor(centers_long$cluster)

ggplot(centers_long) +
  geom_bar( aes(x=scale, y=score, fill=cluster), stat="identity", alpha=0.5, position = position_dodge()) 
  
#scale_x_discrete(limits = c("dexterity", "gait_speed", "grip_strength", "walk_enduro"))

#FINAL CLUSTERS FOR 3

final_clust3 <- kmeans(toolbox, centers = 3)
final_clust3
hd8$cluster3 <- final_clust3$cluster

#create df of center of clusters values
centers3 <- as_tibble(final_clust3[["centers"]])
centers3$cluster = c(1,2,3)

# RUN BAR PLOTS TO VIZUALIZE CLUSTER CENTER

# 3 
centers3_long <- centers3 %>%
  pivot_longer(!cluster, names_to = "scale", values_to = "score")

centers3_long$cluster <- as.factor(centers3_long$cluster)

ggplot(centers3_long) +
  geom_bar( aes(x=scale, y=score, fill=cluster), stat="identity", alpha=0.5, position = position_dodge()) 

```
# test differences in cognition between cutser groups (phenogroups)
```{r}
library(nlme)
# fluid cognition in whole group
summary(lme(cog_fluid~cluster + sex + age + SES + pds, random=~1|subject_id, data=hd8)) # 2 clusters
summary(lme(cog_fluid~cluster3 + sex + age + SES + pds, random=~1|subject_id, data=hd8)) # 3 clusters

# crystal cognition in whole group
summary(lme(cog_crystal~cluster + sex + age + SES + pds, random=~1|subject_id, data=hd8)) # 2 clusters
summary(lme(cog_crystal~cluster3 + sex + age + SES + pds, random=~1|subject_id, data=hd8)) # 3 clusters
summary(lme(cog_crystal~pa + sex + age + SES + pds, random=~1|subject_id, data=hd8)) # 3 clusters

#total cognition
summary(lme(cog_total~cluster + sex + age + SES + pds, random=~1|subject_id, data=hd8)) # 2 clusters
summary(lme(cog_total~cluster3 + sex + age + SES + pds, random=~1|subject_id, data=hd8)) # 3 clusters

library(ggstatsplot)
plt <- ggbetweenstats(
  data = hd8,
  x = pa,
  y = cog_fluid) + 
  theme(
    axis.ticks = element_blank(),
    axis.line = element_line(colour = "grey50"),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    panel.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
    plot.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4")
    )
plt
# https://www.r-graph-gallery.com/web-violinplot-with-ggstatsplot.html 


plt <- plt  +
  theme(
    axis.ticks = element_blank(),
    axis.line = element_line(colour = "grey50"),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    panel.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
    plot.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4")
  )
plt


```
# create MRI ids
```{r}
load(file = "completness.Rdata")
ids <- tibble(completeness$src_subject_id)
ids <- dplyr::rename(ids, subject_id = `completeness$src_subject_id`)
```
# merge behav ids with NDA MRI ids
```{r}
#merge with MRI ids only
hd8i <- left_join(ids, hd8, by = "subject_id")
# complete data only
hd8i <- na.omit(hd8i)

# #hdi is behav ids (n=933),minus those under age 8 (N=837) with comeplte data (N=595), after gait_speed outliers removed (N593) merged with imaging ids (n=652) with complete data (n=374-total)
save(hd8i, file = "hd8i.Rdata") # see above comment

load(file = "hd8i.Rdata")
# export list of IDS for imaging analysis
subject_ids <- as_tibble(hd8i$subject_id)
write.csv(subject_ids, file = "hd8i_sub_ids.csv")

#export covars for FSGD file
write.csv(hd8i, file = "hd8i.csv")

# classify sport performance based on cluster assingment 

```
#bootstrap explore
```{r}
library(fpc)

par(mfrow = c(3, 4))

clustBoot <- clusterboot(toolbox, B = 100,
                         clustermethod = kmeansCBI,
                         k = 2, seed = 12345,
                         showplots = TRUE)
clustBoot # gives jaccard index 
```
# import sub-cortical volumes
```{r}
library(readr)
aseg_vol <- read_table2("/work/cbhlab/Tim/hcpdifreesurfer_1/aseg.vol.table")
View(aseg_vol)

library(stringr)
aseg_vol <- aseg_vol %>%
      mutate_at("subject_id", str_replace, "_V1_MR", "")

# merge hippocampal and eTIV to hd8 df
hippamy <- aseg_vol %>% 
  select(subject_id, LeftHippocampus, RightHippocampus, LeftAmygdala, RightAmygdala, EstimatedTotalIntraCranialVol)

# merge with hd8i

hd8i <- left_join(hd8i, hippamy, by = "subject_id")

```
# test for differences in sub cortical volumes between clusters/groups 
```{r}
# fluid cognition in whole group
summary(lme(LeftHippocampus~cluster + sex + age + SES + pds + EstimatedTotalIntraCranialVol, random=~1|subject_id, data=hd8i)) # 2 clusters
summary(lme(LeftHippocampus~cluster3 + sex + age + SES + pds + EstimatedTotalIntraCranialVol, random=~1|subject_id, data=hd8i)) # 3 clusters

summary(lme(RightHippocampus~cluster + sex + age + SES + pds + EstimatedTotalIntraCranialVol, random=~1|subject_id, data=hd8i)) # 2 clusters
summary(lme(RightHippocampus~cluster3 + sex + age + SES + pds + EstimatedTotalIntraCranialVol, random=~1|subject_id, data=hd8i)) # 3 clusters

summary(lme(LeftAmygdala~cluster + sex + age + SES + pds + EstimatedTotalIntraCranialVol, random=~1|subject_id, data=hd8i)) # 2 clusters
summary(lme(LeftAmygdala~cluster3 + sex + age + SES + pds + EstimatedTotalIntraCranialVol, random=~1|subject_id, data=hd8i)) # 3 clusters

summary(lme(RightAmygdala~cluster + sex + age + SES + pds + EstimatedTotalIntraCranialVol, random=~1|subject_id, data=hd8i)) # 2 clusters
summary(lme(RightAmygdala~cluster3 + sex + age + SES + pds + EstimatedTotalIntraCranialVol, random=~1|subject_id, data=hd8i)) # 3 clusters

```

                         
                         